# Generated by Django 5.0 on 2026-04-21 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['user', 'date'], name='core_prayer_user_id_f2e5d9_idx'),
        ),
    ]
